### ISSUE TITLE
Syriac in non-Syriac environment in sidebar

### ISSUE THREAD

**Issue by tutebatti** [tutebatti/FLExhmtl2XeLaTeX#19]
@gkiraz Already in the FLEx output, there is some Syriac text in a sidebar not marked as such, cf. the entry ܐܡܪ (Sedra ID 171). Is this only temporarily the case or will it remain like this? (Note that also the xhtml+css as such don't look good.)

**Comment by gkiraz** [comment]
Ah, the text of the notes for boxes has these special codes that SIL added
when importing the data. I think they have to do with font changes (e.g.
italics, etc.). I am not too worried about them and the content of these
fields will be edited for the future edition and whoever edits them will
get rid of these code. Just dump the data as is for now.

Best,

George
__________________________
George A. Kiraz, M.St. (Oxon), M.Phil., Ph.D. (Cantab)
Gorgias Press, Editor-in-Chief

Institute for Advanced Study, Princeton, Senior Research Associate — ܡܦܫܩܢܐ
ܡܚܝܠܐ
Princeton University, Lecturer in Near Eastern Studies (Syriac) — ܕܒܫܡ
ܒܠܚܘܕ ܡܩܪܝܢܐ

954 River Rd., Piscataway, NJ 08854 USA
www.gorgiaspress.com
